### ISSUE TITLE
Add Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-venus-fly-traps#13]
## User Story
As a user, I should be able to add messages by clicking enter.

## AC
**Given** A user navigates to your page
**Then** they type in the input field
**And** when they hit enter a new message should be created
**And** the message should show up in the new chat window

## Dev Notes
* In message_input.js create a keypress event that calls a function addMessage 
* addMessage grabs the text added to the input field using `$('#message-input').val();` and saves it to a variable called `messageInput`
* The function then calls the setMessage() function to push `messageInput` to the message array in messageData
* reference #17 to print the message to the DOM so it shows up in the chat window

**Comment by joeypetrone** [comment]
Sample Keypress Code:

```js
$('#passwd').keypress(function(e) {
    if (e.which == '13') {
        submitLogin();
    }
});
