### ISSUE TITLE
Clear Messages

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-venus-fly-traps#14]
## User Story
As a user, when I have messages, I should be able to clear them out with a single button.

As a user, when I DON'T have messages, I should not be able to click the clear button

## AC
**Given** A user navigates to your page
**Then** they see a bunch of messages
**And** they click the clear button
**And** the chat history should get cleared out

**Given** A user navigates to your page
**And** they see no messages
**Then** the clear button should be disabled.

## Dev Notes
*Create a click event that calls a function clearMessages that calls  `clear-button` id and get the messagesArray and reeassigns it to an empty array and calls the setMessages to be resaved as an empty array. 
*Recall the messageBuilder function.
*${'#clear-button}.disabled = true
*Click event lives in the `init` function.

**Comment by joeypetrone** [comment]
Bootstrap disable button:
https://getbootstrap.com/docs/4.0/components/buttons/#disabled-state

**Comment by joeypetrone** [comment]
W3Schools `disabled` Demo:
https://www.w3schools.com/code/tryit.asp?filename=GCPPHP1UH2YO
