### ISSUE TITLE
Large Text

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-venus-fly-traps#15]
## User Story
As a user, with tired eyes, I should be able to chat with large text.

## AC
**Given** A user navigates to your page
**Then** they should see a checkbox below the input field called "Large Text"
**And** they should be able to click this checkbox
**And** when the checkbox is selected all the message text should be larger

## Dev Notes
*Create a div class called `form-check  form-check-inline` in html.
*Create an input tag that inserts a checkbox type.  Reference comments for bootstrap code. Give id of `big-text-checkbox`.
*Create a click event that calls the toggle class jquery function called toggleTextSize.   
*Toggle text size should use jquery to target the messages div called '#message-container'  and reference the comment below to change font size style.
*Click event lives in `init` function on main.js.

**Comment by joeypetrone** [comment]
This may be nice if it is allowed:
https://www.flaticon.com/free-icon/font_2087807?term=text%20size&page=1&position=1

**Comment by joeypetrone** [comment]
Bootstrap forms has a checkbox:
https://getbootstrap.com/docs/4.0/components/forms/

**Comment by joeypetrone** [comment]
Bootstrap link to inline form checkbox:
https://getbootstrap.com/docs/4.0/components/forms/#inline

**Comment by joeypetrone** [comment]
Javascript for changing text size:
https://www.w3schools.com/jsref/prop_style_fontsize.asp
