### ISSUE TITLE
Delete Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-venus-fly-traps#16]
## User Story
As a user I should be able to delete messages my messages.

## AC
**Given** A message on your page
**Then** there should be a delete button for each message (that belongs to your user)
**And** when the button is pushed the message should no longer exist

## Dev Notes
* Use the delete button from bootstrap link below which will remove message from the dom.
* Button will have id that is equal to message id.
* Click event will check to see if message id matches  button id. See comments below.

**Comment by joeypetrone** [comment]
Bootstrap alerts can be closed using dismiss:
https://getbootstrap.com/docs/4.0/components/alerts/#dismissing

**Comment by joeypetrone** [comment]
Use this for reference:
```js
const deleteDinoEvent = (e) => {
  const dinoId = e.target.closest('.card').id;
  const dinoPosition = dinos.findIndex((p) => p.id === dinoId);
  dinos.splice(dinoPosition, 1);
  buildAllDinos(dinos);
};
