### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-venus-fly-traps#2]
## User Story
As a user, with sensitive eyes, I should be able to chat using a dark theme.

## AC
**Given** A user navigates to your page
**Then** they should see a checkbox below the input field called "Dark Theme"
**And** they should be able to click this checkbox
**And** when the checkbox is selected the page should show a dark theme with lightly colored text

## Dev Notes
*Create a div class called `form-check  form-check-inline` in html.
*Create an input tag that inserts a checkbox type.  Reference comments for bootstrap code. 
Give id of `dark-mode-checkbox`.
*Create a click event that calls the function toggleDarkMode that will use the jquery toggle class method to add a dark-mode class to the body tag.  
*In main.scss create a .dark-mode, add a black background and white text to style.

**Comment by lstar18** [comment]
https://www.w3schools.com/howto/howto_js_toggle_dark_mode.asp

**Comment by joeypetrone** [comment]
These font awesomes may work as well:
https://fontawesome.com/icons/toggle-off?style=solid
https://fontawesome.com/icons/toggle-on?style=solid

**Comment by joeypetrone** [comment]
Bootstrap forms has a checkbox:
https://getbootstrap.com/docs/4.0/components/forms/

**Comment by John-Fleming** [comment]
When unchecking the button, the navbar class styles wouldn't change back, so had to add a conditional that looked for the check state of the button and reset class changes if the status of the button was unchecked
