### ISSUE TITLE
Multiple Users

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-venus-fly-traps#6]
## User Story
As a user, when on the page I should be able to send messages from my user.

## AC
**WHEN** the page loads
**THEN** I should see some way to select my user
**AND** when I add messages my user should get credit

## Dev Notes:

1. Create a helpers/data/userData.js file that holds an array of users (*see example below*).
1. Create a `getUsers` function in userData that returns the array of users and export that function
1. Create a components/users/user.js file that imports the `getUsers` function and the `printToDom` function from utils
1. Create a `printUsers` domString builder function that loops through the users array and calls `printToDom` to push the users to the `#users-dropdown` div
1. The `printUsers` function should add a Bootstrap radio button group with each user's name and each button should be assigned an ID that is equal to the `user.id`  - https://getbootstrap.com/docs/4.4/components/buttons/#checkbox-and-radio-buttons
1. Refer to #18 to print message with username .
```js
const users = [
  { id: 'user1', name: 'Xavier' },
  { id: 'user2', name: 'Joanna' },
  { id: 'user3', name: 'Gunter' },
  { id: 'user4', name: 'Sven' },
  { id: 'user5', name: 'Mackenzie' }
];
```

**Comment by joeypetrone** [comment]
Bootstrap link to inline form checkbox:
https://getbootstrap.com/docs/4.0/components/forms/#inline

**Comment by John-Fleming** [comment]
Decided to do a Bootstrap dropdown instead of of the radio buttons because it looks better.
